apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maintenance-jobs
  namespace: tooling
spec:
  destination:
    namespace: tooling
    server: https://kubernetes.default.svc
  project: tooling
  source:
    path: manifests
    repoURL: https://github.com/corest/argodemo-project-maintenance-jobs.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      prune: false
      selfHeal: true

