apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: argocd
spec:
  destination:
    namespace: tooling
    server: https://kubernetes.default.svc
  project: projects
  source:
    path: manifests
    repoURL: https://github.com/corest/argodemo-projects.git
    targetRevision: demo
  syncPolicy:
    automated:
      allowEmpty: true
      prune: false
      selfHeal: true
